// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: service.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Control_Type int32

const (
	Control_TYPE_UNSPECIFIED Control_Type = 0
	Control_TYPE_REGISTER    Control_Type = 1
	Control_TYPE_QUIT        Control_Type = 2
	Control_TYPE_PING        Control_Type = 3
	Control_TYPE_PONG        Control_Type = 4
)

// Enum value maps for Control_Type.
var (
	Control_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_REGISTER",
		2: "TYPE_QUIT",
		3: "TYPE_PING",
		4: "TYPE_PONG",
	}
	Control_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_REGISTER":    1,
		"TYPE_QUIT":        2,
		"TYPE_PING":        3,
		"TYPE_PONG":        4,
	}
)

func (x Control_Type) Enum() *Control_Type {
	p := new(Control_Type)
	*p = x
	return p
}

func (x Control_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Control_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (Control_Type) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x Control_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Control_Type.Descriptor instead.
func (Control_Type) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1, 0}
}

type Chat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginPath      string                 `protobuf:"bytes,1,opt,name=origin_path,json=originPath,proto3" json:"origin_path,omitempty"`
	DestinationPath string                 `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	Direct          bool                   `protobuf:"varint,3,opt,name=direct,proto3" json:"direct,omitempty"`
	Mention         bool                   `protobuf:"varint,4,opt,name=mention,proto3" json:"mention,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetOriginPath() string {
	if x != nil {
		return x.OriginPath
	}
	return ""
}

func (x *Chat) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *Chat) GetDirect() bool {
	if x != nil {
		return x.Direct
	}
	return false
}

func (x *Chat) GetMention() bool {
	if x != nil {
		return x.Mention
	}
	return false
}

type Control struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Control_Type           `protobuf:"varint,2,opt,name=type,proto3,enum=tenyks.service.v1.Control_Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	HelpText      string                 `protobuf:"bytes,5,opt,name=help_text,json=helpText,proto3" json:"help_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Control) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Control) GetType() Control_Type {
	if x != nil {
		return x.Type
	}
	return Control_TYPE_UNSPECIFIED
}

func (x *Control) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Control) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Control) GetHelpText() string {
	if x != nil {
		return x.HelpText
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Chat
	//	*Message_Control
	Payload       isMessage_Payload      `protobuf_oneof:"payload"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,30,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetChat() *Chat {
	if x != nil {
		if x, ok := x.Payload.(*Message_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Message) GetControl() *Control {
	if x != nil {
		if x, ok := x.Payload.(*Message_Control); ok {
			return x.Control
		}
	}
	return nil
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Chat struct {
	Chat *Chat `protobuf:"bytes,1,opt,name=chat,proto3,oneof"`
}

type Message_Control struct {
	Control *Control `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

func (*Message_Chat) isMessage_Payload() {}

func (*Message_Control) isMessage_Payload() {}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x11tenyks.service.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n" +
	"\x04Chat\x12\x1f\n" +
	"\vorigin_path\x18\x01 \x01(\tR\n" +
	"originPath\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\x12\x16\n" +
	"\x06direct\x18\x03 \x01(\bR\x06direct\x12\x18\n" +
	"\amention\x18\x04 \x01(\bR\amention\"\xff\x01\n" +
	"\aControl\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.tenyks.service.v1.Control.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\thelp_text\x18\x05 \x01(\tR\bhelpText\"\\\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTYPE_REGISTER\x10\x01\x12\r\n" +
	"\tTYPE_QUIT\x10\x02\x12\r\n" +
	"\tTYPE_PING\x10\x03\x12\r\n" +
	"\tTYPE_PONG\x10\x04\"\xd0\x01\n" +
	"\aMessage\x12-\n" +
	"\x04chat\x18\x01 \x01(\v2\x17.tenyks.service.v1.ChatH\x00R\x04chat\x126\n" +
	"\acontrol\x18\x02 \x01(\v2\x1a.tenyks.service.v1.ControlH\x00R\acontrol\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x1e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\t\n" +
	"\apayload2\xa9\x01\n" +
	"\x0eMessageService\x12N\n" +
	"\x0eStreamMessages\x12\x1a.tenyks.service.v1.Message\x1a\x1a.tenyks.service.v1.Message\"\x00(\x010\x01\x12G\n" +
	"\vSendMessage\x12\x1a.tenyks.service.v1.Message\x1a\x1a.tenyks.service.v1.Message\"\x00B)Z'github.com/kyleterry/tenyks/internal/pbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(Control_Type)(0),             // 0: tenyks.service.v1.Control.Type
	(*Chat)(nil),                  // 1: tenyks.service.v1.Chat
	(*Control)(nil),               // 2: tenyks.service.v1.Control
	(*Message)(nil),               // 3: tenyks.service.v1.Message
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	0, // 0: tenyks.service.v1.Control.type:type_name -> tenyks.service.v1.Control.Type
	1, // 1: tenyks.service.v1.Message.chat:type_name -> tenyks.service.v1.Chat
	2, // 2: tenyks.service.v1.Message.control:type_name -> tenyks.service.v1.Control
	4, // 3: tenyks.service.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	3, // 4: tenyks.service.v1.MessageService.StreamMessages:input_type -> tenyks.service.v1.Message
	3, // 5: tenyks.service.v1.MessageService.SendMessage:input_type -> tenyks.service.v1.Message
	3, // 6: tenyks.service.v1.MessageService.StreamMessages:output_type -> tenyks.service.v1.Message
	3, // 7: tenyks.service.v1.MessageService.SendMessage:output_type -> tenyks.service.v1.Message
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[2].OneofWrappers = []any{
		(*Message_Chat)(nil),
		(*Message_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
