#!/bin/bash

PIDFILE=/run/tenyks.pid
CONF=/etc/tenyks/settings.py
EXEC=`which tenyks`
USER=tenyks
GROUP=tenyks

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting tenyks..."
		if start-stop-daemon --start --oknodo --quiet --exec $EXEC \
			--pidfile $PIDFILE --chuid $USER:$GROUP \
			--background -- $CONF; then
			echo "Running"
		else
			echo "Failed"
			exit 1
		fi
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
		start-stop-daemon --stop --oknodo --quiet --exec $EXEC \
			--pidfile $PIDFILE --chuid $USER:$GROUP \
			--background -- $CONF
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Tenyks to shutdown ..."
                    sleep 1
                done
                echo "Tenyks stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
